#! /bin/sh

for p in 02 03 05 07 11 13 17 19 23 29 31 37 41 43 47
do
   echo "Checking prime number base $p..."

   ./test_qrnsequence -p 10 -s -d 12 seq 20${p} 0 10000 > hintlib_nied${p}.txt

   if test $? -ne 0; then
      echo "test_qrnsequence failed!"
      exit 1
   fi

cat <<EOF | (cd toms738 ; genin) > toms738_nied${p}.txt
12
${p}
10000
0
EOF

./numericdiff hintlib_nied${p}.txt toms738_nied${p}.txt || exit 1

rm hintlib_nied${p}.txt toms738_nied${p}.txt

done

exit 0
